### ISSUE TITLE
What is "uuid" in entity_info?

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-contrib/match_redirect#3]
https://github.com/kreynen/match_redirect/blob/7.x-1.x/match_redirect.module#L19

I've never seen that key before, and I think it can be deleted.

**Comment by kreynen** [comment]
Is it related to https://www.drupal.org/project/entity_uuid.  It's been in the code for 5+ years https://github.com/kreynen/match_redirect/blame/37cbed7e004835b1aaf522b7800b5ed13baf1905/match_redirect.module#L21, but I don't know why you would need to explicitly declare FALSE unless entity_uuid adds a uuid to all entities and this caused a problem with this module?  

I agree that it can be removed in Backdrop.
